import {
  iDevRequest,
  iDevResponse,
  iDevDataUpdate,
  DevDataCreate,
  DevResult,
  DevRequestKeys,
  DevReader,
  DevReaderResult,
} from "./developers.interface";
import {
  iDevInfoRequest,
  iDevInfoResponse,
  iDevInfoDataUpdate,
  DevInfoDataCreate,
  DevInfoRequestKeys,
  DevInfoRequestOSValue,
  DevInfoResult,
} from "./developer_infos.interface";
import {
  iProjRequest,
  iProjResponse,
  ProjDataCreate,
  ProjResult,
  ProjRequestKeys,
  ProjReader,
  ProjReaderResult,
} from "./projects.interface";
import { iTechnology, iTechResponse } from "./technlogies.interface";

export {
  iDevRequest,
  iDevResponse,
  iDevDataUpdate,
  DevDataCreate,
  DevResult,
  DevRequestKeys,
  DevReader,
  DevReaderResult,
  iDevInfoRequest,
  iDevInfoResponse,
  iDevInfoDataUpdate,
  DevInfoDataCreate,
  DevInfoRequestKeys,
  DevInfoRequestOSValue,
  DevInfoResult,
  iProjRequest,
  iProjResponse,
  ProjDataCreate,
  ProjResult,
  ProjRequestKeys,
  ProjReader,
  ProjReaderResult,
  iTechnology,
  iTechResponse,
};
